// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreatinganewboardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void creatinganewboard() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(602, 743));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("add_new_board")).click();
    driver.findElement(By.id("board_name")).sendKeys("@123!{0");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("#boards_nav span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#boards_nav span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("View all boards")).click();
    driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("#\\33--123-0 > .inner")).click();
    driver.findElement(By.linkText("Boards")).click();
    {
      WebElement element = driver.findElement(By.linkText("Boards"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("View all boards")).click();
    driver.findElement(By.cssSelector("#\\33--123-0 > .inner")).click();
    driver.findElement(By.cssSelector(".inner")).click();
    driver.findElement(By.linkText("cancel")).click();
    driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
  }
}
