// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class CreatinganewboardTest {
  private WebDriver driver;
  private WebDriverWait wait;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void createANewBoard() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(550, 691));

    // Click the first button (e.g., "Sign In")
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();

    // Click "Add New Board"
    wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board"))).click();

    // Enter board name
    WebElement boardNameInput = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("board_name")));
    boardNameInput.sendKeys("@123!{0");

    // Submit board creation
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();

    // Open Boards Nav
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("#boards_nav span"))).click();

    // Click "View all boards"
    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("View all boards"))).click();

    // Click the newly created board
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("h4"))).click();

    // Verify board name
    String boardTitle = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("h3"))).getText();
    assertThat(boardTitle, is("@123!{0"));
  }
}
